import type { Metadata } from "next";
import localFont from "next/font/local";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const Aston = localFont({
  src: "./fonts/Aston-Script.woff",
  variable: "--font-aston-script",
  weight: "100 900",
});

const HankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken-grotesk",
  weight: ["100", "200", "300", "400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "EcoBetty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Aston.variable} ${HankenGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
